export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ASSETS_SUCCESS = 'LOAD_ASSETS_SUCCESS';
export const CREATE_ASSET_SUCCESS = 'CREATE_ASSET_SUCCESS';
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS';
